using MyHordesOptimizerApi.DiscordBot.Enums;

namespace MyHordesOptimizerApi.DiscordBot.Localization
{
    public sealed partial class BotTexts
    {
        public static readonly BotTexts Fr = new BotTexts
        {
            Locale = Locales.Fr,

            GenericError = error => $"Une erreur s'est produite\n```{error}```",
            CommandFailed = reason => $"Une erreur est survenue : {reason}",

            AntiAbuseResetMessage = "Le compteur anti-abus a été réinitialisé !",
            AntiAbuseStarted = target => $"Le compteur anti-abus a été lancé ! Vous serez notifié {target} dans 15 minutes.",
            TimerScheduled = target => $"Votre compteur a bien été programmé ! Vous serez notifié {target}.",
            TimerNotCreated = "Le compteur n'a pas pu être créé.",
            TimerCreationError = error => $"Une erreur s'est produite lors de la création du compteur\n```{error}```",
            TimerReasonEmpty = "La raison ne peut pas être vide.",
            TimerReasonTooLong = max => $"La raison ne peut pas dépasser {max} caractères.",
            TimerTooMany = (count, max) => $"Vous avez déjà {count} compteurs en cours, le maximum est {max}.",
            TimerReasonField = "Raison",
            TimerExpirationField = "Expiration",
            TimerDurationFormatHelp = "Format attendu : 1Y 2M 7D 1h 25m 12s (Y années, M mois, D jours, h heures, m minutes, s secondes).",
            TimerDurationUnreadable = "Durée illisible.",
            TimerDurationRepeatedUnit = unit => $"L'unité « {unit} » apparaît plusieurs fois.",
            TimerDurationTooLong = "Durée trop longue.",
            TimerDurationNotPositive = "La durée doit être supérieure à zéro.",
            TimerSentLate = dueUnixSeconds => $"-# Prévu <t:{dueUnixSeconds}:f>, envoyé en retard.",
            TimerTargetHere = "ici",
            TimerTargetHerePrivate = "ici, par un message visible de vous seul",
            TimerTargetDirectMessage = "par message privé",
            TimerTargetDirectMessageFallback = "par message privé (le bot ne peut pas écrire ici)",

            AttackEstimationsTitle = day => $"Estimations pour le jour {day}",
            AttackCalculated = (day, min, max) => $"*Attaque J{day} calculée* : {min} - {max}",
            AttackPlannerField = day => $"Planificateur J{day}",
            AttackEstimationField = day => $"Estimation J{day}",
            AttackSentByDirectMessage = "Estimations envoyées en message privé",
            AttackError = error => $"Une erreur s'est produite lors de la récupération des estimations\n```{error}```",

            InstructionsDraftNotFound = "Le brouillon des consignes est introuvable : relancez la commande /instructions.",
            InstructionsMaxSections = "Impossible d'ajouter une section : Discord limite un message à 25 sections.",
            InstructionsAddTitle = "Ajouter un titre",
            InstructionsUpdateTitle = "Modifier le titre",
            InstructionsAddDescription = "Ajouter une description",
            InstructionsUpdateDescription = "Modifier la description",
            InstructionsAddSection = "Ajouter une section",
            InstructionsAddSectionLimitReached = "Ajouter une section (limite atteinte)",
            InstructionsPublish = "Publier les consignes",
            InstructionsPublishError = error => $"Les consignes n'ont pas pu être publiées\n```{error}```",
            InstructionsTitleEmpty = "Le titre ne peut pas être vide.",
            InstructionsDescriptionEmpty = "La description ne peut pas être vide.",
            InstructionsSectionEmpty = "Le titre et le contenu d'une section ne peuvent pas être vides.",
            InstructionsTooLong = (length, max) => $"Modification refusée : les consignes compteraient {length} caractères, au-delà de la limite "
                                                   + $"Discord de {max} (titre, description et sections compris).",
            InstructionsFull = (element, max) => $"Impossible d'ajouter {element} : les consignes atteignent la limite Discord de "
                                                 + $"{max} caractères (titre, description et sections compris).",
            InstructionsElementTitle = "un titre",
            InstructionsElementDescription = "une description",
            InstructionsElementSection = "une section",
            InstructionsTitleLabel = "Titre",
            InstructionsDescriptionLabel = "Description",
            InstructionsSectionTitleLabel = "Titre de la section",
            InstructionsSectionContentLabel = "Contenu de la section",

            FeedbackSuggestionModalTitle = "Envoyer une suggestion",
            FeedbackSuggestionTitleLabel = "Titre de la suggestion",
            FeedbackSuggestionDetailsLabel = "Détails de la suggestion",
            FeedbackSuggestionPosted = "La suggestion a bien été postée",
            FeedbackBugModalTitle = "Signaler un bug",
            FeedbackBugTitleLabel = "Titre du bug",
            FeedbackBugDetailsLabel = "Détails du bug",
            FeedbackBugPosted = "Le bug a bien été signalé",

            FaqGoToWebsite = "Aller au site",
            FaqGoToTutorial = "Aller au tutoriel",
            FaqChromeExtension = "Extension Chrome",
            FaqFirefoxExtension = "Extension Firefox",
            FaqInstallScript = "Installer le script",
            FaqGhoulTitle = "Chances de devenir goule",
            FaqMseTitle = "Résultats de la consommation de MSE",
            FaqValueLine = (label, percent) => $"{label} : {percent}%",
            ItemMeatyBone = "Os charnu",
            ItemFleshroomPuree = "Purée de charognardes",
            ItemHumanFlesh = "Viande humaine",
            ItemTravellersCorpse = "Cadavre d'un voyageur",
            FaqMseGivesAp = actionPoints => $"Donne {actionPoints} PA",
            FaqMseGivesApAndAddiction = actionPoints => $"Donne {actionPoints} PA + addiction",
            FaqMseTerrorises = "Terrorise",
            FaqMseNoEffect = "Ne fait rien",
            FaqCampingTitle = "Chances de survie en camping",
            CheatBold = "gras",
            CheatItalic = "italique",
            CheatUnderline = "souligné",
            CheatStrikethrough = "barré",
            CheatSpoiler = "spoiler",
            CheatCode = "bloc de texte",
            CheatQuote = "citation",
            CheatMultilineCode = "bloc de texte\nsur plusieurs lignes",
            CheatMultilineQuote = "Citation\nsur plusieurs lignes",
            CheatMaskedLink = "Lien masqué",
            CheatBigTitle = "Gros titre",
            CheatMediumTitle = "Moyen titre",
            CheatSmallTitle = "Petit titre",
            CheatSmallText = "Petit texte",
            CheatBulletList = "Liste à puce",
            CheatOrderedList = "Liste ordonnée",
            CheatLevel = level => $"Niveau {level}",
            CheatSpacesHint = "(les ⋅ représentent les espaces)",

            GlossaryNoMatch = searchValue => $"Aucune correspondance n'a été trouvée pour {searchValue}",

            RecipeError = error => $"Une erreur s'est produite lors de la récupération de l'objet\n```{error}```",
            RecipeNoResult = "Aucun résultat n'a été trouvé",
            RecipeTruncated = count => count > 1
                ? $"Résultats tronqués : {count} recettes non affichées"
                : $"Résultats tronqués : {count} recette non affichée",
            RecipeComponents = "Composants",
            RecipeResults = "Résultats",

            TranslateSearchExpired = "Cette recherche a expiré : relancez la commande /traduire pour parcourir ses résultats.",
            TranslateSentByDirectMessage = "Les traductions seront envoyées par message privé",
            TranslateNoResult = searchValue => $"Aucune traduction trouvée pour {searchValue}",
            TranslateError = error => $"Une erreur s'est produite lors de la récupération des traductions\n```{error}```",
            TranslatePrevious = "Précédent",
            TranslateNext = "Suivant",

            PlayRock = "Pierre",
            PlayPaper = "Feuille",
            PlayScissors = "Ciseaux",
            PlayHeads = "Face",
            PlayTails = "Pile",
            PlayCardRanks = new[] { "As", "Roi", "Dame", "Valet", "10", "9", "8", "7", "6", "5", "4", "3", "2" },
            PlayCardSuits = new[] { "Cœur", "Trèfle", "Carreau", "Pique" },
            PlayCard = (rank, suit) => $"{rank} de {suit}"
        };
    }
}
