/** Une emoticone du forum MyHordes (tag + fichier). */
export interface Emote {
    readonly tag: string;
    readonly src: string;
}

/** Emoticones du forum MyHordes, groupe "emotes" (cf. EmoteDataService.php cote jeu). */
export const EMOTES: readonly Emote[] = [
    { tag: ':mh:', src: 'img/hordes_img/emotes/favicon.ico' },
    { tag: ':smile:', src: 'img/hordes_img/emotes/smile.gif' },
    { tag: ':sad:', src: 'img/hordes_img/emotes/sad.gif' },
    { tag: ':blink:', src: 'img/hordes_img/emotes/blink.gif' },
    { tag: ':surprise:', src: 'img/hordes_img/emotes/surprise.gif' },
    { tag: ':lol:', src: 'img/hordes_img/emotes/lol.gif' },
    { tag: ':thinking:', src: 'img/hordes_img/emotes/thinking.gif' },
    { tag: ':neutral:', src: 'img/hordes_img/emotes/neutral.gif' },
    { tag: ':rage:', src: 'img/hordes_img/emotes/rage.gif' },
    { tag: ':angry:', src: 'img/hordes_img/emotes/angry.gif' },
    { tag: ':sleep:', src: 'img/hordes_img/emotes/sleep.gif' },
    { tag: ':wink:', src: 'img/hordes_img/emotes/wink.gif' },
    { tag: ':horror:', src: 'img/hordes_img/emotes/horror.gif' },
    { tag: ':zhead:', src: 'img/hordes_img/emotes/zhead.gif' },
    { tag: ':sick:', src: 'img/hordes_img/emotes/sick.gif' },
    { tag: ':chat:', src: 'img/hordes_img/emotes/chat.gif' },
    { tag: ':calim:', src: 'img/hordes_img/emotes/calim.gif' },
    { tag: ':xmas:', src: 'img/hordes_img/emotes/xmas.gif' },
    { tag: ':scout:', src: 'img/hordes_img/emotes/scout.gif' },
    { tag: ':scav:', src: 'img/hordes_img/emotes/scav.gif' },
    { tag: ':surv:', src: 'img/hordes_img/emotes/surv.gif' },
    { tag: ':guard:', src: 'img/hordes_img/emotes/guard.gif' },
    { tag: ':tech:', src: 'img/hordes_img/emotes/tech.gif' },
    { tag: ':tamer:', src: 'img/hordes_img/emotes/tamer.gif' },
    { tag: ':basic:', src: 'img/hordes_img/emotes/basic.gif' },
    { tag: ':sham:', src: 'img/hordes_img/emotes/sham.gif' },
    { tag: ':guide:', src: 'img/hordes_img/emotes/guide.gif' },
    { tag: ':ghoul:', src: 'img/hordes_img/emotes/ghoul.gif' },
    { tag: ':iloveu:', src: 'img/hordes_img/emotes/iloveu.gif' },
    { tag: ':sock:', src: 'img/hordes_img/emotes/socks.gif' },
    { tag: ':clean:', src: 'img/hordes_img/emotes/clean.gif' },
    { tag: ':rptext:', src: 'img/hordes_img/emotes/rptext.gif' },
    { tag: ':proscout:', src: 'img/hordes_img/emotes/proscout.gif' },
    { tag: ':proguard:', src: 'img/hordes_img/emotes/proguard.gif' },
    { tag: ':proscav:', src: 'img/hordes_img/emotes/proscav.gif' },
    { tag: ':prosurv:', src: 'img/hordes_img/emotes/prosurv.gif' },
    { tag: ':protamer:', src: 'img/hordes_img/emotes/protamer.gif' },
    { tag: ':protech:', src: 'img/hordes_img/emotes/protech.gif' },
    { tag: ':prosham:', src: 'img/hordes_img/emotes/prosham.gif' },
    { tag: ':butcher:', src: 'img/hordes_img/emotes/butcher.gif' },
    { tag: ':zombie:', src: 'img/hordes_img/emotes/zombie.gif' },
    { tag: ':camper:', src: 'img/hordes_img/emotes/camper.gif' },
    { tag: ':cannibal:', src: 'img/hordes_img/emotes/cannibal.gif' },
    { tag: ':night:', src: 'img/hordes_img/emotes/night.gif' },
    { tag: ':maso:', src: 'img/hordes_img/emotes/maso.gif' },
    { tag: ':thief:', src: 'img/hordes_img/emotes/thief.gif' },
    { tag: ':pillage:', src: 'img/hordes_img/emotes/pillage.gif' },
    { tag: ':santa:', src: 'img/hordes_img/emotes/santa.gif' },
    { tag: ':goodg:', src: 'img/hordes_img/emotes/goodg.gif' },
    { tag: ':ermwin:', src: 'img/hordes_img/emotes/ermwin.gif' },
    { tag: ':cdhwin:', src: 'img/hordes_img/emotes/cdhwin.gif' },
    { tag: ':defwin:', src: 'img/hordes_img/emotes/defwin.gif' },
    { tag: ':pande:', src: 'img/hordes_img/emotes/pande.gif' },
    { tag: ':lepre:', src: 'img/hordes_img/emotes/lepre.gif' },
    { tag: ':tamwin:', src: 'img/hordes_img/emotes/tamwin.gif' },
    { tag: ':rangwin:', src: 'img/hordes_img/emotes/rangwin.gif' },
    { tag: ':techwin:', src: 'img/hordes_img/emotes/techwin.gif' },
    { tag: ':derwin:', src: 'img/hordes_img/emotes/derwin.gif' },
    { tag: ':ripflash:', src: 'img/hordes_img/emotes/ripflash.gif' },
    { tag: ':rrefer:', src: 'img/hordes_img/emotes/rrefer.gif' },
    { tag: ':noob:', src: 'img/hordes_img/emotes/noob.gif' },
    { tag: ':wound:', src: 'img/hordes_img/emotes/wound.gif' },
    { tag: ':cooked:', src: 'img/hordes_img/emotes/cooked.gif' }
];

/**
 * Icones MyHordes, groupe "default" (cf. EmoteDataService.php cote jeu, bloc "// Others").
 * 4 tags i18n (ap/pc/pm/ep) figes sur leur variante .fr.gif : le site est mono-langue francaise cote UI.
 * Regeneration : parser le bloc "// Others" du fichier source (packages/myhordes-fixtures/src/templates/Service/EmoteDataService.php
 * dans le depot MyHordes clone), ne garder que les entrees dont 'index' est numerique (les alias FR/EN partagent
 * le meme fichier et portent 'index'=> -1 : :pa:/:ap:, :cp:/:pc:, :mp:/:pm:, :pe:/:ep:).
 */
export const DEFAULT_ICONS: readonly Emote[] = [
    { tag: ':home:', src: 'img/hordes_img/emotes/home.gif' },
    { tag: ':gate:', src: 'img/hordes_img/emotes/gate.gif' },
    { tag: ':water:', src: 'img/hordes_img/emotes/water.gif' },
    { tag: ':human:', src: 'img/hordes_img/emotes/human.gif' },
    { tag: ':heal:', src: 'img/hordes_img/emotes/heal.gif' },
    { tag: ':drug:', src: 'img/hordes_img/emotes/drug.gif' },
    { tag: ':death:', src: 'img/hordes_img/emotes/death.gif' },
    { tag: ':bone:', src: 'img/hordes_img/emotes/bone.gif' },
    { tag: ':bag:', src: 'img/hordes_img/emotes/bag.gif' },
    { tag: ':soul:', src: 'img/hordes_img/emotes/soul.gif' },
    { tag: ':refine:', src: 'img/hordes_img/emotes/refine.gif' },
    { tag: ':warning:', src: 'img/hordes_img/emotes/warning.gif' },
    { tag: ':done:', src: 'img/hordes_img/forum/done.png' },
    { tag: ':remove:', src: 'img/hordes_img/icons/small_remove.gif' },
    { tag: ':bp:', src: 'img/hordes_img/emotes/bp.gif' },
    { tag: ':fortify:', src: 'img/hordes_img/emotes/fortify.gif' },
    { tag: ':def:', src: 'img/hordes_img/emotes/def.gif' },
    { tag: ':camp:', src: 'img/hordes_img/emotes/camp.gif' },
    { tag: ':sites:', src: 'img/hordes_img/emotes/sites.gif' },
    { tag: ':arrowleft:', src: 'img/hordes_img/emotes/arrowleft.gif' },
    { tag: ':middot:', src: 'img/hordes_img/emotes/middot.gif' },
    { tag: ':arrowright:', src: 'img/hordes_img/emotes/arrowright.gif' },
    { tag: ':arma:', src: 'img/hordes_img/emotes/arma.gif' },
    { tag: ':ap:', src: 'img/hordes_img/emotes/ap.fr.gif' },
    { tag: ':pc:', src: 'img/hordes_img/emotes/pc.fr.gif' },
    { tag: ':pm:', src: 'img/hordes_img/emotes/pm.fr.gif' },
    { tag: ':ep:', src: 'img/hordes_img/emotes/sp.fr.gif' },
    { tag: ':build:', src: 'img/hordes_img/emotes/build.gif' },
    { tag: ':repair:', src: 'img/hordes_img/emotes/repair.gif' },
    { tag: ':wonder:', src: 'img/hordes_img/emotes/wonder.gif' },
    { tag: ':tasty:', src: 'img/hordes_img/emotes/tasty.gif' },
    { tag: ':deco:', src: 'img/hordes_img/emotes/deco.gif' },
    { tag: ':buried:', src: 'img/hordes_img/emotes/buried.gif' },
    { tag: ':ban:', src: 'img/hordes_img/emotes/ban.gif' },
    { tag: ':extreme:', src: 'img/hordes_img/emotes/extreme.gif' },
    { tag: ':psoul:', src: 'img/hordes_img/emotes/psoul.gif' },
    { tag: ':alc:', src: 'img/hordes_img/emotes/alc.gif' },
    { tag: ':chain:', src: 'img/hordes_img/emotes/chain.gif' },
    { tag: ':batgun:', src: 'img/hordes_img/emotes/batgun.gif' },
    { tag: ':watergun:', src: 'img/hordes_img/emotes/watergun.gif' },
    { tag: ':brd:', src: 'img/hordes_img/emotes/brd.gif' },
    { tag: ':castle:', src: 'img/hordes_img/emotes/castle.gif' },
    { tag: ':crow:', src: 'img/hordes_img/emotes/crow.gif' },
    { tag: ':wheel:', src: 'img/hordes_img/emotes/wheel.gif' },
    { tag: ':chest:', src: 'img/hordes_img/emotes/chest.gif' },
    { tag: ':collect:', src: 'img/hordes_img/emotes/collect.gif' },
    { tag: ':ruin:', src: 'img/hordes_img/emotes/ruin.gif' },
    { tag: ':explo:', src: 'img/hordes_img/emotes/explo.gif' },
    { tag: ':dexplo:', src: 'img/hordes_img/emotes/dexplo.gif' },
    { tag: ':texplo:', src: 'img/hordes_img/emotes/texplo.gif' },
    { tag: ':drag:', src: 'img/hordes_img/emotes/drag.gif' },
    { tag: ':shower:', src: 'img/hordes_img/emotes/shower.gif' },
    { tag: ':cburn:', src: 'img/hordes_img/emotes/cburn.gif' },
    { tag: ':experimental:', src: 'img/hordes_img/emotes/experimental.gif' },
    { tag: ':fight:', src: 'img/hordes_img/emotes/fight.gif' },
    { tag: ':hero:', src: 'img/hordes_img/emotes/hero.gif' },
    { tag: ':lms:', src: 'img/hordes_img/emotes/lms.gif' },
    { tag: ':hclms:', src: 'img/hordes_img/emotes/hclms.gif' },
    { tag: ':zen:', src: 'img/hordes_img/emotes/zen.gif' },
    { tag: ':infect:', src: 'img/hordes_img/emotes/infect.gif' },
    { tag: ':lab:', src: 'img/hordes_img/emotes/lab.gif' },
    { tag: ':lock:', src: 'img/hordes_img/emotes/lock.gif' },
    { tag: ':last:', src: 'img/hordes_img/emotes/last.gif' },
    { tag: ':mystic:', src: 'img/hordes_img/emotes/mystic.gif' },
    { tag: ':nuke:', src: 'img/hordes_img/emotes/nuke.gif' },
    { tag: ':ranked:', src: 'img/hordes_img/emotes/ranked.gif' },
    { tag: ':legend:', src: 'img/hordes_img/emotes/legend.gif' },
    { tag: ':rep:', src: 'img/hordes_img/emotes/rep.gif' },
    { tag: ':trash:', src: 'img/hordes_img/emotes/trash.gif' },
    { tag: ':watch:', src: 'img/hordes_img/emotes/watch.gif' },
    { tag: ':ginfec:', src: 'img/hordes_img/emotes/ginfec.gif' },
    { tag: ':share:', src: 'img/hordes_img/emotes/share.gif' },
    { tag: ':bgum:', src: 'img/hordes_img/emotes/bgum.gif' },
    { tag: ':ptame:', src: 'img/hordes_img/emotes/ptame.gif' },
    { tag: ':cott:', src: 'img/hordes_img/emotes/cott.gif' },
    { tag: ':gsp:', src: 'img/hordes_img/emotes/gsp.gif' },
    { tag: ':ufc:', src: 'img/hordes_img/emotes/ufc.gif' },
    { tag: ':part:', src: 'img/hordes_img/emotes/winthi.gif' },
    { tag: ':comu:', src: 'img/hordes_img/emotes/comu.gif' },
    { tag: ':comu2:', src: 'img/hordes_img/emotes/comu2.gif' },
    { tag: ':easter:', src: 'img/hordes_img/emotes/paques.gif' },
    { tag: ':sand:', src: 'img/hordes_img/emotes/sandb.gif' },
    { tag: ':explor:', src: 'img/hordes_img/emotes/exploration.gif' },
    { tag: ':scaddh:', src: 'img/hordes_img/emotes/scaddh.gif' },
    { tag: ':probasic:', src: 'img/hordes_img/emotes/probasic.gif' },
    { tag: ':eventwin:', src: 'img/hordes_img/emotes/eventwin.gif' },
    { tag: ':eventpart:', src: 'img/hordes_img/emotes/eventpart.gif' },
    { tag: ':thermal:', src: 'img/hordes_img/emotes/thermal.gif' },
    { tag: ':decofeist:', src: 'img/hordes_img/emotes/decofeist.gif' }
];

export interface UnicodeEmoji {
    readonly char: string;
    readonly label: string;
}

export interface UnicodeEmojiGroup {
    readonly title: string;
    readonly emojis: readonly UnicodeEmoji[];
}

/** Set curate d'emojis Unicode usuels, groupes par theme. */
export const UNICODE_EMOJIS: readonly UnicodeEmojiGroup[] = [
    {
        title: 'Visages & émotions',
        emojis: [
            { char: '😀', label: 'Sourire large' },
            { char: '😃', label: 'Sourire yeux ouverts' },
            { char: '😄', label: 'Sourire yeux souriants' },
            { char: '😁', label: 'Grand sourire' },
            { char: '😆', label: 'Rire aux éclats' },
            { char: '😅', label: 'Rire gêné' },
            { char: '🤣', label: 'Écroulé de rire' },
            { char: '😂', label: 'Larme de rire' },
            { char: '🙂', label: 'Léger sourire' },
            { char: '🙃', label: "Sourire à l'envers" },
            { char: '😉', label: "Clin d'œil" },
            { char: '😊', label: 'Sourire content' },
            { char: '😇', label: 'Auréole' },
            { char: '🥰', label: 'Amoureux' },
            { char: '😍', label: 'Cœur dans les yeux' },
            { char: '🤩', label: 'Étoiles dans les yeux' },
            { char: '😘', label: 'Bisou' },
            { char: '😗', label: 'Bisou léger' },
            { char: '😚', label: 'Bisou fermé' },
            { char: '😙', label: 'Bisou souriant' },
            { char: '😋', label: 'Gourmand' },
            { char: '😛', label: 'Langue tirée' },
            { char: '😜', label: "Clin d'œil langue tirée" },
            { char: '🤪', label: 'Fou dingue' },
            { char: '😝', label: 'Langue tirée fermée' },
            { char: '🤑', label: 'Argent' },
            { char: '🤗', label: 'Câlin' },
            { char: '🤭', label: 'Main sur la bouche' },
            { char: '🤫', label: 'Chut' },
            { char: '🤔', label: 'Réflexion' },
            { char: '🤐', label: 'Bouche fermée' },
            { char: '🤨', label: 'Sourcil levé' },
            { char: '😐', label: 'Neutre' },
            { char: '😑', label: 'Sans expression' },
            { char: '😶', label: 'Sans bouche' },
            { char: '😏', label: 'Sourire narquois' },
            { char: '😒', label: 'Blasé' },
            { char: '🙄', label: 'Yeux au ciel' },
            { char: '😬', label: 'Grimace' },
            { char: '🤥', label: 'Menteur' }
        ]
    },
    {
        title: 'Personnes & gestes',
        emojis: [
            { char: '👋', label: 'Salut' },
            { char: '🤚', label: 'Main levée' },
            { char: '🖐', label: 'Main ouverte' },
            { char: '✋', label: 'Stop' },
            { char: '🖖', label: 'Salut vulcain' },
            { char: '👌', label: 'Ok' },
            { char: '🤌', label: 'Pincée de doigts' },
            { char: '🤏', label: 'Petit peu' },
            { char: '✌', label: 'Victoire' },
            { char: '🤞', label: 'Doigts croisés' },
            { char: '🤟', label: "Je t'aime (signe)" },
            { char: '🤘', label: 'Cornes' },
            { char: '🤙', label: 'Appelle-moi' },
            { char: '👈', label: 'Pointe à gauche' },
            { char: '👉', label: 'Pointe à droite' },
            { char: '👆', label: 'Pointe en haut' },
            { char: '🖕', label: "Doigt d'honneur" },
            { char: '👇', label: 'Pointe en bas' },
            { char: '☝', label: 'Index levé' },
            { char: '👍', label: "Pouce en l'air" },
            { char: '👎', label: 'Pouce en bas' },
            { char: '✊', label: 'Poing levé' },
            { char: '👊', label: 'Coup de poing' },
            { char: '🤛', label: 'Poing gauche' },
            { char: '🤜', label: 'Poing droit' }
        ]
    },
    {
        title: 'Nature & animaux',
        emojis: [
            { char: '🐶', label: 'Chien' },
            { char: '🐱', label: 'Chat' },
            { char: '🐭', label: 'Souris' },
            { char: '🐹', label: 'Hamster' },
            { char: '🐰', label: 'Lapin' },
            { char: '🦊', label: 'Renard' },
            { char: '🐻', label: 'Ours' },
            { char: '🐼', label: 'Panda' },
            { char: '🐨', label: 'Koala' },
            { char: '🐯', label: 'Tigre' },
            { char: '🦁', label: 'Lion' },
            { char: '🐮', label: 'Vache' },
            { char: '🐷', label: 'Cochon' },
            { char: '🐸', label: 'Grenouille' },
            { char: '🐵', label: 'Singe' },
            { char: '🙈', label: 'Singe qui ne voit pas' },
            { char: '🙉', label: "Singe qui n'entend pas" },
            { char: '🙊', label: 'Singe qui ne parle pas' },
            { char: '🐔', label: 'Poule' },
            { char: '🐧', label: 'Manchot' },
            { char: '🐦', label: 'Oiseau' },
            { char: '🐤', label: 'Poussin' },
            { char: '🦆', label: 'Canard' },
            { char: '🦅', label: 'Aigle' },
            { char: '🦉', label: 'Hibou' }
        ]
    },
    {
        title: 'Nourriture & boisson',
        emojis: [
            { char: '🍏', label: 'Pomme verte' },
            { char: '🍎', label: 'Pomme rouge' },
            { char: '🍐', label: 'Poire' },
            { char: '🍊', label: 'Mandarine' },
            { char: '🍋', label: 'Citron' },
            { char: '🍌', label: 'Banane' },
            { char: '🍉', label: 'Pastèque' },
            { char: '🍇', label: 'Raisin' },
            { char: '🍓', label: 'Fraise' },
            { char: '🍈', label: 'Melon' },
            { char: '🍒', label: 'Cerises' },
            { char: '🍑', label: 'Pêche' },
            { char: '🥭', label: 'Mangue' },
            { char: '🍍', label: 'Ananas' },
            { char: '🥥', label: 'Noix de coco' },
            { char: '🥝', label: 'Kiwi' },
            { char: '🍅', label: 'Tomate' },
            { char: '🍆', label: 'Aubergine' },
            { char: '🥑', label: 'Avocat' },
            { char: '🥦', label: 'Brocoli' },
            { char: '🍞', label: 'Pain' },
            { char: '🥐', label: 'Croissant' },
            { char: '🥨', label: 'Bretzel' },
            { char: '🧀', label: 'Fromage' },
            { char: '🍗', label: 'Cuisse de poulet' }
        ]
    },
    {
        title: 'Activités & objets',
        emojis: [
            { char: '⚽', label: 'Ballon de foot' },
            { char: '🏀', label: 'Ballon de basket' },
            { char: '🏈', label: 'Ballon de foot US' },
            { char: '⚾', label: 'Balle de baseball' },
            { char: '🥎', label: 'Balle de softball' },
            { char: '🎾', label: 'Balle de tennis' },
            { char: '🏐', label: 'Ballon de volley' },
            { char: '🏉', label: 'Ballon de rugby' },
            { char: '🎱', label: 'Boule de billard' },
            { char: '🏓', label: 'Ping-pong' },
            { char: '🏸', label: 'Badminton' },
            { char: '🎮', label: 'Manette de jeu' },
            { char: '🎲', label: 'Dé' },
            { char: '🎯', label: 'Cible' },
            { char: '🎳', label: 'Bowling' },
            { char: '🎸', label: 'Guitare' },
            { char: '🎺', label: 'Trompette' },
            { char: '🎻', label: 'Violon' },
            { char: '🥁', label: 'Tambour' },
            { char: '🎨', label: 'Palette de peinture' },
            { char: '🎬', label: 'Clap de cinéma' },
            { char: '📷', label: 'Appareil photo' },
            { char: '🎁', label: 'Cadeau' },
            { char: '🏆', label: 'Trophée' },
            { char: '🥇', label: "Médaille d'or" }
        ]
    },
    {
        title: 'Symboles & cœurs',
        emojis: [
            { char: '❤', label: 'Cœur rouge' },
            { char: '🧡', label: 'Cœur orange' },
            { char: '💛', label: 'Cœur jaune' },
            { char: '💚', label: 'Cœur vert' },
            { char: '💙', label: 'Cœur bleu' },
            { char: '💜', label: 'Cœur violet' },
            { char: '🖤', label: 'Cœur noir' },
            { char: '🤍', label: 'Cœur blanc' },
            { char: '🤎', label: 'Cœur marron' },
            { char: '💔', label: 'Cœur brisé' },
            { char: '❣', label: "Point d'exclamation cœur" },
            { char: '💕', label: 'Deux cœurs' },
            { char: '💞', label: 'Cœurs qui tournent' },
            { char: '💓', label: 'Cœur qui bat' },
            { char: '💗', label: 'Cœur qui grandit' },
            { char: '💖', label: 'Cœur étincelant' },
            { char: '💘', label: 'Cœur flèche' },
            { char: '💝', label: 'Cœur cadeau' },
            { char: '✨', label: 'Étincelles' },
            { char: '🔥', label: 'Feu' }
        ]
    }
];
