name: (Script) Update Version

on:
  workflow_dispatch

jobs:
  script-change-version:    
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@main

      - name: Read Script
        id: script
        uses: juliangruber/read-file-action@v1
        with:
          path: ./Scripts/Tampermonkey/my_hordes_optimizer.user.js

          
      - name: Write Complete Script
        run: echo "${{ steps.script.outputs.content }}"
        
      - name: Match Version
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match-test
        with:
          text:     "// @version    1.0.0-beta.60"
          regex:     '@version *(.+)'
          flags:     gm
          
      - name: Write Script Test
        run: echo "${{ steps.regex-match-test.outputs }}"

      - name: Match Version
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text:     ${{ steps.script.outputs }}
          regex:     '@version *(.+)'
          flags:     gm
          
      - name: Write Script
        run: echo "${{ steps.regex-match.outputs }}"

      - name: Test Save Script In Variable
        run: |
          file_content=${{ steps.script.outputs.content }} >> $GITHUB_ENV

      - name: Test Read Variable
        run: |
          echo "${{ env.file_content }}
