name: (Script) Update Version

on:
  workflow_dispatch

jobs:
  script-change-version:    
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@main

      - name: Read Script
        id: script
        uses: juliangruber/read-file-action@v1
        with:
          path: ./Scripts/Tampermonkey/my_hordes_optimizer.user.js

      - name: Read Script 3
        id: script-test-3
        run: sed -n 3p ./Scripts/Tampermonkey/my_hordes_optimizer.user.js
          
      - name: Read Script 4
        run: echo "test4=$(sed -n 3p ./Scripts/Tampermonkey/my_hordes_optimizer.user.js)" >> $GITHUB_OUTPUT

      - name: regex-match-file
        id: test
        uses: noahreinalter/regex-match-file@latest
        with:
          # The regex pattern you want to use as a string
          regex_pattern: '@version *(.+)'
          # The path to the file as a string
          path: './Scripts/Tampermonkey/my_hordes_optimizer.user.js'
        
      - name: Test Read Variable
        run: |
          echo "Read Script 3. ${{ steps.script-test-3 }}"
          echo "Read Script 3.1 ${{ steps.script-test-3.outputs }}"
          echo "Read Script ${{ steps.test.outputs }}"
          echo "Read Script 4. ${{ env.test4 }}"
          echo "Read Script 4.1 ${{ env.test4.outputs }}"

      - name: Match Version
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text:     ${{ steps.script.outputs.content }}
          regex:     '@version *(.+)'
          flags:     gm
          
      - name: Write Script
        run: echo "${{ steps.regex-match.outputs }}"
