name: (Script) Update Version

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Scripts/Tampermonkey/my_hordes_optimizer.user.js'

jobs:
  script-change-version:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Read Script
        id: read-script
        run: echo "version_row=$(sed -n 3p ./Scripts/Tampermonkey/my_hordes_optimizer.user.js)" >> $GITHUB_OUTPUT

      - name: Match Version
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ steps.read-script.outputs.version_row }}
          regex: '@version *(.+)'

      - name: Get Script Version
        id: get-version
        env:
          VERSION: "${{ steps.regex-match.outputs.group1 }}"
        run: echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Save version
        run: |
          curl --request POST \
            --url "https://api.myhordesoptimizer.fr/Parameters/Parameters" \
            --header "Content-Type: application/json" \
            --header "Authorization: Basic ${{secrets.AUTHENTICATION_BASIC}}" \
            --data '{"name": "ScriptVersion", "value": "${{ steps.get-version.outputs.version }}"}'
