name: (Script) Update Version

on:
  workflow_dispatch

jobs:
  script-change-version:    
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@main

      - name: Read Script
        id: script
        uses: juliangruber/read-file-action@v1
        with:
          path: ./Scripts/Tampermonkey/my_hordes_optimizer.user.js

      - name: Read Script 3
        id: script-test
        run: |
          sed -n 3p ./Scripts/Tampermonkey/my_hordes_optimizer.user.js

      - name: Match Version
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match-test2
        with:
          text:     sed -n 3p ./Scripts/Tampermonkey/my_hordes_optimizer.user.js
          regex:     '@version *(.+)'
          flags:     gm

      - name: Test Read Variable
        run: |
          echo "Read Script 3. ${{ steps.script-test[0] }}"
          echo "Read Script 3. ${{ steps.script-test.outputs[0] }}"
          echo "Read Script 3.1 ${{ steps.script-test.outputs }}"
          echo "Read Script 4. ${{ steps.regex-match-test2 }}"
          echo "Read Script 4.1 ${{ steps.regex-match-test2.outputs }}"
          
      - name: Match Version
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match-test
        with:
          text:     sed -n 3p ./Scripts/Tampermonkey/my_hordes_optimizer.user.js
          regex:     '@version *(.+)'
          flags:     gm

      - name: Match Version
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text:     ${{ steps.script.outputs.content }}
          regex:     '@version *(.+)'
          flags:     gm
          
      - name: Write Script
        run: echo "${{ steps.regex-match.outputs }}"
