name: (Script) Update Version

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - 'Scripts/Tampermonkey/my_hordes_optimizer.user.js'

jobs:
    #    script-change-version:
    #
    #        runs-on: ubuntu-latest
    #
    #        steps:
    #            -   uses: actions/checkout@main
    #
    #            -   name: Read Script
    #                id: read-script
    #                run: echo "version_row=$(sed -n 3p ./Scripts/Tampermonkey/my_hordes_optimizer.user.js)" >> $GITHUB_OUTPUT
    #
    #            -   name: Match Version
    #                uses: actions-ecosystem/action-regex-match@v2
    #                id: regex-match
    #                with:
    #                    text: ${{ steps.read-script.outputs.version_row }}
    #                    regex: '@version *(.+)'
    #
    #            -   name: Get Script Version
    #                id: get-version
    #                env:
    #                    VERSION: "${{ steps.regex-match.outputs.group1 }}"
    #                run: echo "version=$VERSION" >> $GITHUB_OUTPUT
    #
    #            -   name: Save version
    #                run: |
    #                    curl --request POST \
    #                      --url "https://api.myhordesoptimizer.fr/Parameters/Parameters" \
    #                      --header "Content-Type: application/json" \
    #                      --header "Authorization: Basic ${{secrets.AUTHENTICATION_BASIC}}" \
    #                      --data '{"name": "ScriptVersion", "value": "${{ steps.get-version.outputs.version }}"}'

    deploy_chrome_extension:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@main

            -   name: Zip
                uses: vimtor/action-zip@v1.1
                with:
                    files: Extensions/Chrome/
                    dest: Chrome.zip

            -   name: Publish
                uses: wdzeng/chrome-extension@v1
                with:
                    extension-id: jolghobcgphmgaiachbipnpiimmgknno
                    zip-path: ${{ github.workspace }}/Chrome.zip
                    client-id: ${{ secrets.CHROME_EXTENSION_CLIENT_ID }}
                    client-secret: ${{ secrets.CHROME_EXTENSION_CLIENT_SECRET }}
                    refresh-token: ${{ secrets.CHROME_EXTENSION_REFRESH_TOKEN }}

    deploy_firefox_extension:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@main

            -   name: Zip
                uses: vimtor/action-zip@v1.1
                with:
                    files: Extensions/Firefox/
                    dest: Firefox.zip

            -   name: Publish
                uses: wdzeng/firefox-addon@v1
                with:
                    addon-guid: 14876417-17c6-417d-80bb-b18c5b40c366
                    xpi-path: ${{ github.workspace }}/Firefox.zip
                    self-hosted: false
                    jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
                    jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}
