name: (Script) Update Version

on:
  workflow_dispatch

jobs:
  script-change-version:    
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@main

#      - name: Read Script
#        id: script
#        uses: juliangruber/read-file-action@v1
#        with:
#          path: ./Scripts/Tampermonkey/my_hordes_optimizer.user.js

      - name: Read Script
        id: read-script
        run: echo "test=$(sed -n 3p ./Scripts/Tampermonkey/my_hordes_optimizer.user.js)" >> $GITHUB_OUTPUT
        
      - name: Test Read Variable
        run: |
          echo "Read Script 1a ${{ steps.read-script.outputs.test }}"

      - name: Test Read Variable 2        
        env:
          STEPS: ${{ toJSON(steps) }}
          SCRIPT: ${{ toJSON(steps.read-script) }}
        run: |
          echo "$STEPS"
          echo "$SCRIPT"

      - name: Match Version
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text:     ${{ steps.read-script.outputs.test }}
          regex:     '@version *(.+)'
          
      - name: Write Script
        env:
          MATCH: ${{ toJSON(steps.regex-match.outputs) }}
        run: |
          echo "${{ steps.regex-match.outputs }}"
          echo "$MATCH"
