name: (Script) Update Version

on:
  workflow_dispatch

jobs:
  script-change-version:    
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@main

      - name: Read Script
        id: read-script
        run: echo "version=$(sed -n 3p ./Scripts/Tampermonkey/my_hordes_optimizer.user.js)" >> $GITHUB_OUTPUT

      - name: Match Version
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text:     ${{ steps.read-script.outputs.version }}
          regex:     '@version *(.+)'
          
      - name: Get Script Version
        env:
          VERSION: "${{ steps.regex-match.outputs.group1 }}"
        run: |
          echo "$VERSION"
          
      - name: Save version
        env:
          VERSION: "${{ steps.regex-match.outputs.group1 }}"
          DATA: '{"name": "ScriptVersion", "value": $VERSION}'
        run: |
          echo "$VERSION"
          echo "$DATA"
          curl --request POST \
            --url 'https://api.myhordesoptimizer.fr/Parameters/Parameters' \
            --header 'Content-Type: application/json' \
            --data $DATA
#            --user "<YOUR_CLIENT_ID>:<YOUR_CLIENT_SECRET>" \
