name: (Script) Update Version

on:
  workflow_dispatch

jobs:
  script-change-version:    
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@main

      - name: Read Script
        id: script
        uses: juliangruber/read-file-action@v1
        with:
          path: ./Scripts/Tampermonkey/my_hordes_optimizer.user.js

      - name: Read Script 2
        run: |
          sed -n 3p ./Scripts/Tampermonkey/my_hordes_optimizer.user.js

      - name: Read Script 3
        run: |
          file_content=sed -n 3p ./Scripts/Tampermonkey/my_hordes_optimizer.user.js >> $GITHUB_ENV

      - name: Test Read Variable
        run: |
          echo "${{ env.file_content }}
          
      - name: Match Version
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match-test
        with:
          text:     "// @version    1.0.0-beta.60"
          regex:     '@version *(.+)'
          flags:     gm

      - name: Match Version
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text:     ${{ steps.script.outputs.content }}
          regex:     '@version *(.+)'
          flags:     gm
          
      - name: Write Script
        run: echo "${{ steps.regex-match.outputs }}"
