name: (Script) Update Version

on:
  workflow_dispatch

jobs:
  script-change-version:    
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@main

      - name: Read Script
        id: script
        uses: juliangruber/read-file-action@v1
        with:
          path: ./Scripts/Tampermonkey/my_hordes_optimizer.user.js

      - name: Read Script 1
        id: read-script-A
        run: sed -n 3p ./Scripts/Tampermonkey/my_hordes_optimizer.user.js

      - name: Read Script 1a
        id: read-script-1a
        run: echo "test=sed -n 3p ./Scripts/Tampermonkey/my_hordes_optimizer.user.js" >> $GITHUB_OUTPUT
          
      - name: Read Script 2
        run: echo "test2=$(sed -n 3p ./Scripts/Tampermonkey/my_hordes_optimizer.user.js)" >> $GITHUB_OUTPUT

      - name: Read Script 4
        id: script-test-4
        run: head -n 3 ./Scripts/Tampermonkey/my_hordes_optimizer.user.js)
        
      - name: Read Script 3
        run: echo "test3=$(head -n 3 ./Scripts/Tampermonkey/my_hordes_optimizer.user.js)" >> $GITHUB_OUTPUT
        
      - name: Test Read Variable
        run: |
          echo "Read Script 1 ${{ steps.read-script-1 }}"
          echo "Read Script 1a ${{ steps.read-script-1.outputs }}"
          echo "Read Script 1 ${{ steps.read-script-1a }}"
          echo "Read Script 1a ${{ steps.read-script-1a.outputs.test }}"
          echo "Read Script 2 ${{ env.test2 }}"
          echo "Read Script 2a ${{ env.test2.outputs }}"
          echo "Read Script 3 ${{ env.test3 }}"
          echo "Read Script 3a ${{ env.test3.outputs }}"
          echo "Read Script 4 ${{ steps.script-test-4 }}"
          echo "Read Script 4a ${{ steps.script-test-4 }}"

      - name: Match Version
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text:     ${{ steps.script.outputs.content }}
          regex:     '@version *(.+)'
          flags:     gm
          
      - name: Write Script
        run: echo "${{ steps.regex-match.outputs }}"
