name: (Client) Deploy Dev

on:
  workflow_dispatch

jobs:
  firebase-deploy-dev:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./MyHordesOptimizerWebsite/

    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with: 
        node-version: '18.17.0'
        
    - run: npm install
    
    - run: npm run build

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@main
      with:
        args: deploy --only hosting:dev
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
