name: (Client) Deploy Dev

on:
  workflow_dispatch

jobs:
  firebase-deploy-dev:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./MyHordesOptimizerWebsite/

    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with: 
        node-version: '18.17.0'
        
    - run: npm install
    - run: npm install -g firebase-tools
    
    - run: npm run build
    
    - run: firebase use dev --token FIREBASE_TOKEN
    - run: firebase deploy --only hosting:dev --token FIREBASE_TOKEN
