name: (Server) Deploy Prod

on:
    workflow_dispatch:

env:
    DOTNET_ROOT: '.'

jobs:
    build:
        runs-on: windows-latest
        defaults:
            run:
                working-directory: ./MyHordesOptimizerApi

        steps:
            -   uses: actions/checkout@main

            -   name: Set up .NET Core
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: '8.0'
                    include-prerelease: true

            -   name: Build with dotnet
                run: dotnet build --configuration Release

            -   name: dotnet publish sinks
                run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/Serilog.Sinks.Discord

            -   name: dotnet publish api
                run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/MyHordesOptimizerApi

            -   name: Upload artifact for deployment job
                uses: actions/upload-artifact@v4
                with:
                    name: .net-app
                    path: ${{env.DOTNET_ROOT}}/MyHordesOptimizerApi

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: 'production'
            url: 'https://myhordes-optimizer.web.app/'

        steps:
            -   uses: actions/checkout@main

            -   name: Download artifact from build job
                uses: actions/download-artifact@v4
                with:
                    name: .net-app

            -   name: Send to Server
                uses: appleboy/scp-action@v0.1.7
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USERNAME }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    port: ${{ secrets.SSH_PORT }}
                    source: './publish/*'
                    target: "/home/renack/livraison_mho"
                    strip_components: 1

            -   name: Restart Server
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USERNAME }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    port: ${{ secrets.SSH_PORT }}
                    script: ./updateProd.sh
