name: (Server) Deploy Dev

on:
  workflow_dispatch:

env:
  DOTNET_ROOT: '.'

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./MyHordesOptimizerApi

    steps:
      - uses: actions/checkout@main

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish sinks
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/Serilog.Sinks.Discord

      - name: dotnet publish api
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/MyHordesOptimizerApi

      #      - name: Upload sinks for deployment job
      #        uses: actions/upload-artifact@v2
      #        with:
      #          name: .net-sinks
      #          path: ${{env.DOTNET_ROOT}}/Serilog.Sinks.Discord

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/MyHordesOptimizerApi

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'deployment'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: MyHordesOptimizerApi
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_46612d33e3fc456283a3700e421f4a93 }}
          package: .
