name: (Server) Deploy Prod

on:
  workflow_dispatch:

env:
  DOTNET_ROOT: '.'

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./MyHordesOptimizerApi

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/MyHordesOptimizerApi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/MyHordesOptimizerApi

#  deploy:
#    runs-on: windows-latest
#    needs: build
#
#    steps:
#      - name: Login SSH
