name: (Server) Deploy Prod

on:
  workflow_dispatch:

env:
  DOTNET_ROOT: '.'

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./MyHordesOptimizerApi

    steps:
      - uses: actions/checkout@main

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/MyHordesOptimizerApi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/MyHordesOptimizerApi

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@main

      - name: Start Testing
        run: |
          echo "Starting test"

      - name: Test
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            ls -al

      - name: Login SSH
        run: |
          ssh -i ~/.ssh/authorized_keys -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "ls"
          echo "Test completed"
