name: (Client) Deploy Prod

on:
  workflow_dispatch

jobs:
  firebase-deploy-prod:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./MyHordesOptimizerWebsite/

    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with: 
        node-version: '18.17.0'

    - name: Build app
      run: |
        npm install
        npm run build
    - name: Install firebase tools
      run: |
        npm install -g firebase-tools
        firebase use prod --token ${{secrets.FIREBASE_TOKEN}}
        
    - name: Deploy
      run:  firebase deploy --only hosting:prod --token ${{secrets.FIREBASE_TOKEN}}
