name: (Server) Deploy Dev

on:
    workflow_dispatch:

env:
    DOTNET_ROOT: '.'

jobs:
    build:
        runs-on: windows-latest
        defaults:
            run:
                working-directory: ./MyHordesOptimizerApi

        steps:
            -   uses: actions/checkout@main

            -   name: Set up .NET Core
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: '8.0'

            -   name: Build with dotnet
                run: dotnet build --configuration Release

            -   name: Publish projects
                run: |
                    dotnet publish MyHordesOptimizerApi/MyHordesOptimizerApi.csproj -c Release -o ./publish/MyHordesOptimizerApi
                    dotnet publish Serilog.Sinks.Discord/Serilog.Sinks.Discord.csproj -c Release -o ./publish/Serilog.Sinks.Discord

            -   name: Upload artifact for deployment job
                uses: actions/upload-artifact@v4
                with:
                    name: .net-app
                    path: ${{ github.workspace }}\MyHordesOptimizerApi\publish
                    if-no-files-found: error

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: 'production'
            url: 'https://myhordes-optimizer-dev.web.app/'

        steps:
            -   uses: actions/checkout@main

            -   name: Download artifact from build job
                uses: actions/download-artifact@v4
                with:
                    name: .net-app
                    path: ./publish

            -   name: Verify publish directory
                run: | 
                    pwd
                    ls ./publish
    
            -   name: Send to Server
                uses: appleboy/scp-action@v0.1.7
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USERNAME }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    port: ${{ secrets.SSH_PORT }}
                    source: './publish/MyHordesOptimizerApi/*'
                    target: "/home/renack/livraison_mho"
                    strip_components: 2

            -   name: Restart Server
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USERNAME }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    port: ${{ secrets.SSH_PORT }}
                    script: ./updateDev.sh
